MENU_CALLBACK_PREFIX = "menu:"

MENU_HISTORY_CALLBACK = f"{MENU_CALLBACK_PREFIX}history"
MENU_FACTS_CALLBACK = f"{MENU_CALLBACK_PREFIX}facts"
MENU_AVATARS_CALLBACK = f"{MENU_CALLBACK_PREFIX}avatars"
MENU_RESET_CALLBACK = f"{MENU_CALLBACK_PREFIX}reset"
