"""Create tables

Revision ID: 6c41a059cb91
Revises:
Create Date: 2026-03-14 18:24:00.970974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6c41a059cb91"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "avatars",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("current_avatar_id", sa.Uuid(), nullable=True),
        sa.Column("active_chat_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_avatar_id"],
            ["avatars.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_user_id"),
    )
    op.create_table(
        "chats",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("avatar_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "CLOSED", name="chat_status"), nullable=False
        ),
        sa.Column(
            "message_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "completed_turn_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["avatar_id"],
            ["avatars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chats_avatar_id"), "chats", ["avatar_id"], unique=False)
    op.create_index(op.f("ix_chats_user_id"), "chats", ["user_id"], unique=False)
    op.create_index(
        "ix_chats_user_id_status", "chats", ["user_id", "status"], unique=False
    )
    op.create_foreign_key(
        "fk_users_active_chat_id_chats",
        "users",
        "chats",
        ["active_chat_id"],
        ["id"],
    )
    op.create_table(
        "messages",
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("USER", "ASSISTANT", name="message_role"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    op.create_index(
        "ix_messages_chat_id_created_at",
        "messages",
        ["chat_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "memory_facts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("avatar_id", sa.Uuid(), nullable=False),
        sa.Column("fact_text", sa.Text(), nullable=False),
        sa.Column("fact_key", sa.String(length=255), nullable=False),
        sa.Column("source_chat_id", sa.Uuid(), nullable=True),
        sa.Column("source_message_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["avatar_id"],
            ["avatars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "avatar_id",
            "fact_key",
            name="uq_memory_facts_user_avatar_fact_key",
        ),
    )
    op.create_index(
        op.f("ix_memory_facts_avatar_id"), "memory_facts", ["avatar_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_facts_user_id"), "memory_facts", ["user_id"], unique=False
    )
    op.create_index(
        "ix_memory_facts_user_id_avatar_id",
        "memory_facts",
        ["user_id", "avatar_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_memory_facts_user_id_avatar_id", table_name="memory_facts")
    op.drop_index(op.f("ix_memory_facts_user_id"), table_name="memory_facts")
    op.drop_index(op.f("ix_memory_facts_avatar_id"), table_name="memory_facts")
    op.drop_table("memory_facts")
    op.drop_index("ix_messages_chat_id_created_at", table_name="messages")
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_constraint("fk_users_active_chat_id_chats", "users", type_="foreignkey")
    op.drop_index("ix_chats_user_id_status", table_name="chats")
    op.drop_index(op.f("ix_chats_user_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_avatar_id"), table_name="chats")
    op.drop_table("chats")
    op.drop_table("users")
    op.drop_table("avatars")
    # ### end Alembic commands ###
